# Generated by Django 2.1.1 on 2018-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_remove_userdetail_no_of_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='storeid',
            field=models.IntegerField(default=0),
        ),
    ]
