# Generated by Django 2.1.1 on 2018-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_userdetail_storeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='no_of_stores',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
