# Generated by Django 2.1.1 on 2018-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershop',
            name='phone_no',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
