# Generated by Django 2.1.1 on 2018-10-20 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0007_auto_20181018_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), size=500),
        ),
    ]
