# Generated by Django 2.1.1 on 2018-10-20 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_auto_20181020_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
