# Generated by Django 2.1.1 on 2018-10-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_auto_20181020_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shopkeeper',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
